In [1]:
import pandas as pd
from lib.data_utils import fetch_and_prepare_data_all

DATASET_NAME = 'askme-10k'

try:
    data_df = pd.read_csv(f'data_samples/{DATASET_NAME}.csv')
    print('Dataset already exists.')
except FileNotFoundError:
    data_df = await fetch_and_prepare_data_all()
    data_df.to_csv(f'data_samples/{DATASET_NAME}.csv', index=False)
data_df

Dataset already exists.

,_sa_instance_state_question,text_question,paragraph_id,scope,timestamp,downvote,filtered,is_answerable_ic,processed_question,id_question,...,question_id,author_id_answer,processed,_sa_instance_state_rating,text_rating,value,author_id_rating,id_rating,answer_id,timestamp_rating
0,<sqlalchemy.orm.state.InstanceState object at ...,How many passengers can the New Flyer DE60LFA ...,1,single-paragraph,2024-06-26 00:46:58,0,True,True,True,1,...,1,2,True,<sqlalchemy.orm.state.InstanceState object at ...,The answer accurately states the total passeng...,5,3,2,2,2024-06-26 03:56:37
1,<sqlalchemy.orm.state.InstanceState object at ...,What feature does the front door of the Swift ...,1,single-paragraph,2024-06-26 00:46:58,0,True,True,True,2,...,2,2,True,<sqlalchemy.orm.state.InstanceState object at ...,The answer accurately states that the front do...,5,3,4,4,2024-06-26 03:57:23
2,<sqlalchemy.orm.state.InstanceState object at ...,Where are the interior bike racks located on t...,1,single-paragraph,2024-06-26 00:46:58,0,True,True,True,3,...,3,2,True,<sqlalchemy.orm.state.InstanceState object at ...,This answer is fully accurate and detailed. It...,5,3,6,6,2024-06-26 03:57:30
3,<sqlalchemy.orm.state.InstanceState object at ...,Where do the Swift Bus Rapid Transit coaches g...,1,single-paragraph,2024-06-26 00:46:58,0,True,True,True,4,...,4,2,True,<sqlalchemy.orm.state.InstanceState object at ...,The answer provided is fully accurate and deta...,5,3,8,8,2024-06-26 03:57:18
4,<sqlalchemy.orm.state.InstanceState object at ...,Which university's sinking was featured in a l...,3,single-paragraph,2024-06-26 00:46:56,0,True,True,True,5,...,5,2,True,<sqlalchemy.orm.state.InstanceState object at ...,"The answer ""Cambridge University's"" is fully a...",5,3,10,10,2024-06-26 03:57:34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39825,<sqlalchemy.orm.state.InstanceState object at ...,Why was concrete chosen as the material for th...,9999,single-paragraph,2024-06-26 01:03:58,0,True,True,True,39826,...,39826,2,True,<sqlalchemy.orm.state.InstanceState object at ...,The answer provided accurately states that con...,5,3,79652,79652,2024-06-26 07:08:06
39826,<sqlalchemy.orm.state.InstanceState object at ...,Where did Don Dunstan move to in 1972 after se...,10000,single-paragraph,2024-06-26 01:04:23,0,True,True,True,39827,...,39827,2,True,<sqlalchemy.orm.state.InstanceState object at ...,This answer is fully accurate and detailed. It...,5,3,79654,79654,2024-06-26 07:08:05
39827,<sqlalchemy.orm.state.InstanceState object at ...,What happened to the family home after Don Dun...,10000,single-paragraph,2024-06-26 01:04:23,0,True,True,True,39828,...,39828,2,True,<sqlalchemy.orm.state.InstanceState object at ...,"The answer ""The family home was sold"" is mostl...",4,3,79656,79656,2024-06-26 07:08:07
39828,<sqlalchemy.orm.state.InstanceState object at ...,In what year did Don Dunstan's divorce from hi...,10000,single-paragraph,2024-06-26 01:04:23,0,True,True,True,39829,...,39829,2,True,<sqlalchemy.orm.state.InstanceState object at ...,This answer is fully accurate and detailed. It...,5,3,79658,79658,2024-06-26 07:08:09
39829,<sqlalchemy.orm.state.InstanceState object at ...,How did Don Dunstan describe the initial perio...,10000,single-paragraph,2024-06-26 01:04:23,0,True,True,True,39830,...,39830,2,True,<sqlalchemy.orm.state.InstanceState object at ...,This answer is fully accurate and detailed. It...,5,3,79660,79660,2024-06-26 07:07:58

In [7]:
sa_instance_states_columns = [col for col in data_df.columns if '_sa_instance_state' in col]
data_df = data_df.drop(columns=sa_instance_states_columns)
data_df

,text_question,paragraph_id,scope,timestamp,downvote,filtered,is_answerable_ic,processed_question,id_question,context,...,timestamp_answer,question_id,author_id_answer,processed,text_rating,value,author_id_rating,id_rating,answer_id,timestamp_rating
0,How many passengers can the New Flyer DE60LFA ...,1,single-paragraph,2024-06-26 00:46:58,0,True,True,True,1,"In an article about 'Swift Bus Rapid Transit',...",...,2024-06-26 02:37:40,1,2,True,The answer accurately states the total passeng...,5,3,2,2,2024-06-26 03:56:37
1,What feature does the front door of the Swift ...,1,single-paragraph,2024-06-26 00:46:58,0,True,True,True,2,"In an article about 'Swift Bus Rapid Transit',...",...,2024-06-26 02:37:12,2,2,True,The answer accurately states that the front do...,5,3,4,4,2024-06-26 03:57:23
2,Where are the interior bike racks located on t...,1,single-paragraph,2024-06-26 00:46:58,0,True,True,True,3,"In an article about 'Swift Bus Rapid Transit',...",...,2024-06-26 02:37:14,3,2,True,This answer is fully accurate and detailed. It...,5,3,6,6,2024-06-26 03:57:30
3,Where do the Swift Bus Rapid Transit coaches g...,1,single-paragraph,2024-06-26 00:46:58,0,True,True,True,4,"In an article about 'Swift Bus Rapid Transit',...",...,2024-06-26 02:37:21,4,2,True,The answer provided is fully accurate and deta...,5,3,8,8,2024-06-26 03:57:18
4,Which university's sinking was featured in a l...,3,single-paragraph,2024-06-26 00:46:56,0,True,True,True,5,"In an article about 'The Boat Race 1978', sect...",...,2024-06-26 02:37:12,5,2,True,"The answer ""Cambridge University's"" is fully a...",5,3,10,10,2024-06-26 03:57:34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39825,Why was concrete chosen as the material for th...,9999,single-paragraph,2024-06-26 01:03:58,0,True,True,True,39826,"In an article about 'Air well ( condenser )', ...",...,2024-06-26 03:55:27,39826,2,True,The answer provided accurately states that con...,5,3,79652,79652,2024-06-26 07:08:06
39826,Where did Don Dunstan move to in 1972 after se...,10000,single-paragraph,2024-06-26 01:04:23,0,True,True,True,39827,"In an article about 'Don Dunstan', section 'Du...",...,2024-06-26 03:55:47,39827,2,True,This answer is fully accurate and detailed. It...,5,3,79654,79654,2024-06-26 07:08:05
39827,What happened to the family home after Don Dun...,10000,single-paragraph,2024-06-26 01:04:23,0,True,True,True,39828,"In an article about 'Don Dunstan', section 'Du...",...,2024-06-26 03:55:35,39828,2,True,"The answer ""The family home was sold"" is mostl...",4,3,79656,79656,2024-06-26 07:08:07
39828,In what year did Don Dunstan's divorce from hi...,10000,single-paragraph,2024-06-26 01:04:23,0,True,True,True,39829,"In an article about 'Don Dunstan', section 'Du...",...,2024-06-26 03:55:22,39829,2,True,This answer is fully accurate and detailed. It...,5,3,79658,79658,2024-06-26 07:08:09
39829,How did Don Dunstan describe the initial perio...,10000,single-paragraph,2024-06-26 01:04:23,0,True,True,True,39830,"In an article about 'Don Dunstan', section 'Du...",...,2024-06-26 03:55:49,39830,2,True,This answer is fully accurate and detailed. It...,5,3,79660,79660,2024-06-26 07:07:58

In [9]:
data_df.columns

Index(['text_question', 'paragraph_id', 'scope', 'timestamp', 'downvote',
       'filtered', 'is_answerable_ic', 'processed_question', 'id_question',
       'context', 'author_id', 'upvote', 'turns', 'is_answerable_zs',
       'rejected', 'id_paragraph', 'section_name', 'subsubsection_name',
       'section_hierarchy', 'word_count', 'within_page_order',
       'original_entry_id', 'subsection_name', 'page_name', 'text_paragraph',
       'text_cleaned', 'is_bad', 'processed_paragraph', 'id', 'username',
       'hash', 'model', 'prompt', 'id_answer', 'setting', 'text',
       'timestamp_answer', 'question_id', 'author_id_answer', 'processed',
       'text_rating', 'value', 'author_id_rating', 'id_rating', 'answer_id',
       'timestamp_rating'],
      dtype='object')

In [10]:
df_sampled_1_question_per_paragraph = data_df.groupby('paragraph_id').apply(lambda x: x.sample(1)).reset_index(drop=True)
df_sampled_1_question_per_paragraph.to_csv(f'data_samples/{DATASET_NAME}-1-q-per-p.csv', index=False)
df_sampled_1_question_per_paragraph

/tmp/ipykernel_2338278/3291560684.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_sampled_1_question_per_paragraph = data_df.groupby('paragraph_id').apply(lambda x: x.sample(1)).reset_index(drop=True)

,text_question,paragraph_id,scope,timestamp,downvote,filtered,is_answerable_ic,processed_question,id_question,context,...,timestamp_answer,question_id,author_id_answer,processed,text_rating,value,author_id_rating,id_rating,answer_id,timestamp_rating
0,Where are the interior bike racks located on t...,1,single-paragraph,2024-06-26 00:46:58,0,True,True,True,3,"In an article about 'Swift Bus Rapid Transit',...",...,2024-06-26 02:37:14,3,2,True,This answer is fully accurate and detailed. It...,5,3,6,6,2024-06-26 03:57:30
1,Which university's sinking was featured in a l...,3,single-paragraph,2024-06-26 00:46:56,0,True,True,True,5,"In an article about 'The Boat Race 1978', sect...",...,2024-06-26 02:37:12,5,2,True,"The answer ""Cambridge University's"" is fully a...",5,3,10,10,2024-06-26 03:57:34
2,What happens to the Dalek when Rose touches it...,4,single-paragraph,2024-06-26 00:46:56,0,True,True,True,9,In an article about 'Dalek ( Doctor Who episod...,...,2024-06-26 02:37:21,9,2,True,This answer is fully accurate and detailed. It...,5,3,18,18,2024-06-26 03:56:36
3,"Who performed ""Blame Canada"" at the Academy Aw...",5,single-paragraph,2024-06-26 00:47:03,0,True,True,True,15,"In an article about 'South Park : Bigger , Lon...",...,2024-06-26 02:37:40,15,2,True,This answer is fully accurate and detailed. It...,5,3,30,30,2024-06-26 03:57:22
4,What position was Hugh de Cressy named to in t...,6,single-paragraph,2024-06-26 00:46:53,0,True,True,True,19,"In an article about 'Hugh de Cressy', section ...",...,2024-06-26 02:37:27,19,2,True,The answer accurately and fully responds to th...,5,3,38,38,2024-06-26 03:57:27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9952,"Why does Noriko Matsueda create music, accordi...",9996,single-paragraph,2024-06-26 01:03:39,0,True,True,True,39814,"In an article about 'Noriko Matsueda', section...",...,2024-06-26 03:55:38,39814,2,True,The answer accurately quotes Noriko Matsueda's...,5,3,79628,79628,2024-06-26 07:07:47
9953,"What year did T. K. Wetherell take office, mar...",9997,single-paragraph,2024-06-26 01:04:22,0,True,True,True,39818,In an article about 'Florida State University'...,...,2024-06-26 03:55:44,39818,2,True,The answer accurately states that T.K. Wethere...,5,3,79636,79636,2024-06-26 07:08:01
9954,By occupying which region did the Hungarians b...,9998,single-paragraph,2024-06-26 01:04:35,0,True,True,True,39821,In an article about 'Hungarian conquest of the...,...,2024-06-26 03:55:43,39821,2,True,The answer accurately and directly quotes the ...,5,3,79642,79642,2024-06-26 07:08:10
9955,"How tall was Klaphake's later, sugarloaf-shape...",9999,single-paragraph,2024-06-26 01:03:58,0,True,True,True,39824,"In an article about 'Air well ( condenser )', ...",...,2024-06-26 03:55:28,39824,2,True,"The answer accurately quotes the text, providi...",5,3,79648,79648,2024-06-26 07:07:48
9956,In what year did Don Dunstan's divorce from hi...,10000,single-paragraph,2024-06-26 01:04:23,0,True,True,True,39829,"In an article about 'Don Dunstan', section 'Du...",...,2024-06-26 03:55:22,39829,2,True,This answer is fully accurate and detailed. It...,5,3,79658,79658,2024-06-26 07:08:09

In [11]:
import numpy as np
from tqdm.notebook import tqdm
paragraph_ids = data_df['paragraph_id'].unique()
np.random.shuffle(paragraph_ids)

selected_paragraphs = []
total_rows = 0

for pid in tqdm(paragraph_ids):
    if total_rows >= 10000:
        break
    paragraph_rows = data_df[data_df['paragraph_id'] == pid]
    selected_paragraphs.append(paragraph_rows)
    total_rows += len(paragraph_rows)

df_sampled_all_questions_per_paragraph = pd.concat(selected_paragraphs).reset_index(drop=True)
df_sampled_all_questions_per_paragraph.to_csv(f'data_samples/{DATASET_NAME}-all-q-per-p.csv', index=False)
df_sampled_all_questions_per_paragraph

  0%|          | 0/9957 [00:00<?, ?it/s]

,text_question,paragraph_id,scope,timestamp,downvote,filtered,is_answerable_ic,processed_question,id_question,context,...,timestamp_answer,question_id,author_id_answer,processed,text_rating,value,author_id_rating,id_rating,answer_id,timestamp_rating
0,What emotional states does Tim Bayliss observe...,1195,single-paragraph,2024-06-26 00:48:30,0,True,True,True,4738,In an article about 'Subway ( Homicide : Life ...,...,2024-06-26 02:45:46,4738,2,True,"The answer is mostly correct, as it accurately...",4,3,9476,9476,2024-06-26 04:19:20
1,Why was Biedron previously placed in a psychia...,1195,single-paragraph,2024-06-26 00:48:30,0,True,True,True,4739,In an article about 'Subway ( Homicide : Life ...,...,2024-06-26 02:45:41,4739,2,True,This answer is fully accurate and detailed. It...,5,3,9478,9478,2024-06-26 04:19:30
2,What decision does Frank Pembleton make regard...,1195,single-paragraph,2024-06-26 00:48:30,0,True,True,True,4740,In an article about 'Subway ( Homicide : Life ...,...,2024-06-26 02:45:29,4740,2,True,This answer is fully accurate and detailed. It...,5,3,9480,9480,2024-06-26 04:19:23
3,What is the final action taken by Frank Pemble...,1195,single-paragraph,2024-06-26 00:48:30,0,True,True,True,4741,In an article about 'Subway ( Homicide : Life ...,...,2024-06-26 02:45:14,4741,2,True,The answer accurately states the final action ...,5,3,9482,9482,2024-06-26 04:19:24
4,What type of sense is the operator-valued inte...,9759,single-paragraph,2024-06-26 01:04:42,0,True,True,True,38867,In an article about '0 point . This distributi...,...,2024-06-26 03:54:14,38867,2,True,The answer provided is a direct quote from the...,5,3,77734,77734,2024-06-26 07:01:26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,How long did it take for Samoa Joe to retain h...,2189,single-paragraph,2024-06-26 00:50:48,0,True,True,True,8717,"In an article about 'No Surrender ( 2008 )', s...",...,2024-06-26 02:54:12,8717,2,True,This answer is fully accurate and detailed. It...,5,3,17434,17434,2024-06-26 04:39:30
9996,What award did Cheek to Cheek win at the 57th ...,386,single-paragraph,2024-06-26 00:47:34,0,True,True,True,1525,In an article about 'Cheek to Cheek ( album )'...,...,2024-06-26 02:38:58,1525,2,True,This answer is fully accurate and detailed. It...,5,3,3050,3050,2024-06-26 04:03:33
9997,How many copies of Cheek to Cheek were sold in...,386,single-paragraph,2024-06-26 00:47:34,0,True,True,True,1526,In an article about 'Cheek to Cheek ( album )'...,...,2024-06-26 02:38:57,1526,2,True,This answer is fully accurate and detailed. It...,5,3,3052,3052,2024-06-26 04:03:26
9998,What milestone did Lady Gaga achieve by having...,386,single-paragraph,2024-06-26 00:47:34,0,True,True,True,1527,In an article about 'Cheek to Cheek ( album )'...,...,2024-06-26 02:38:58,1527,2,True,The answer accurately states that Lady Gaga be...,5,3,3054,3054,2024-06-26 04:03:01
9999,"Which countries, besides the US, did Cheek to ...",386,single-paragraph,2024-06-26 00:47:34,0,True,True,True,1528,In an article about 'Cheek to Cheek ( album )'...,...,2024-06-26 02:39:08,1528,2,True,This answer is fully accurate and detailed. It...,5,3,3056,3056,2024-06-26 04:03:32